### ISSUE TITLE
Build fails when adding dependency to bsconfig.json

### ISSUE THREAD

**Issue by alltonp** [remithomas/bs-react-native-elements#2]
Hi,

Firstly, thank you for this! Unfortunately, I'm having trouble getting it to work :(

yarn appears to install it just fine, but when I add the dependency the build fails...

bsconfig.json:

`"bs-dependencies": ["reason-react", "reason-react-native", "reason-native-base", "react-native-elements"]`

The error is:

`File "/Users/blah/blah/node_modules/react-native-elements/bsconfig.json", line 1`

The code seems to exist in `/Users/blah/blah/node_modules/bs-react-native-elements`

Where am going wrong?

Many thanks,
Paul

**Comment by remithomas** [comment]
Hello,

sorry for the error. The error is in your `bsconfig.json` try to change your dependency with `bs-react-native-elements` instead of  `react-native-elements`.

https://github.com/remithomas/bs-react-native-elements/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R16

I'm pushing an update.
Thanks for the report :)
